apiVersion: v1
kind: Service
metadata:
  name: spring-server-service
spec:
  ports:
    - name: spring-port
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: back-end
  type: NodePort
