apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - name: post-port
      port: 5432
      targetPort: 5432 
      nodePort: 30000
  selector:
    app: postgres-server
  type: NodePort
